// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Edges struct {
	ID        uuid.UUID    `json:"id"`
	Src       uuid.UUID    `json:"src"`
	Dst       uuid.UUID    `json:"dst"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Links struct {
	ID          uuid.UUID      `json:"id"`
	Url         sql.NullString `json:"url"`
	RetrievedAt sql.NullTime   `json:"retrieved_at"`
}
