// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	EdgesInPartition(ctx context.Context, arg EdgesInPartitionParams) ([]Edges, error)
	FindLink(ctx context.Context, id uuid.UUID) (FindLinkRow, error)
	LinksInPartition(ctx context.Context, arg LinksInPartitionParams) ([]Links, error)
	RemoveStaleEdges(ctx context.Context, arg RemoveStaleEdgesParams) error
	UpsertEdge(ctx context.Context, arg UpsertEdgeParams) (UpsertEdgeRow, error)
	UpsertLink(ctx context.Context, arg UpsertLinkParams) (UpsertLinkRow, error)
}

var _ Querier = (*Queries)(nil)
